### ISSUE TITLE
Howler: when a build is done, trying to build again will fail

### ISSUE THREAD

**Issue by Raffo** [zalando/package-build#15]
This is possible due to this two cleanup lines in the recipe: 

```
    rm_rf "#{builddir}/gobuild/pkg", :verbose => true
    rm_rf "#{builddir}/gobuild/bin", :verbose => true
```

This is the error: 

```
WARNING: Skipping build of howler because build cookie found (/data/recipes/howler/tmp-build/.build-cookie-howler_0_0_8), use "fpm-cook clean" to rebuild!
/var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/path.rb:63:in `install_p': /data/recipes/howler/tmp-build/gobuild/bin/howler does not exist (RuntimeError)
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/path.rb:40:in `install'
    from /data/recipes/howler/recipe.rb:32:in `install'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:160:in `block (2 levels) in dispense'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:138:in `chdir'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:138:in `block in dispense'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:115:in `chdir'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/packager.rb:115:in `dispense'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/cli.rb:113:in `exec'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/cli.rb:77:in `block in execute'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/book.rb:16:in `call'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/book.rb:16:in `load_recipe'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/lib/fpm/cookery/cli.rb:73:in `execute'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
    from /var/lib/gems/1.9.1/gems/fpm-cookery-0.31.0/bin/fpm-cook:7:in `<top (required)>'
    from /usr/local/bin/fpm-cook:23:in `load'
    from /usr/local/bin/fpm-cook:23:in `<main>'
===> Skipping fetch, rev 0.0.8 exists.
===> Using source directory: /data/recipes/howler/tmp-build/howler-tag-0.0.8
===> Installing into /data/recipes/howler/tmp-dest
task ran 1.61386299133 seconds

```

The command used: 

```
fab package_build:ubuntu14.04,howler
```

**Comment by skoenig** [comment]
Fixed since https://github.com/zalando/package-build/commit/02367b9b6a5c2e2dc640bc860abb46f4a97a146c (unified recipes for all MonkeyIsland components)
